# Do not forget to create a new database on your first run:
# $ docker exec -it wiki /script/install.sh <username> <password>
version: '3'
services:
  mediawiki_wiki:
    #build: ./../../../ # Uncomment to build from source
    image: kristophjunge/mediawiki
    container_name: mediawiki_wiki
    env_file: .env.mediawiki
    ports:
    - 8080:8080
    depends_on:
    - mediawiki_mysql
    volumes:
    - mediawiki_images:/images
    - ./logo.png:/var/www/mediawiki/resources/assets/logo.png:ro
    - ./ExtraLocalSettings.php:/var/www/mediawiki/ExtraLocalSettings.php:ro
    - ./extensions/YouTube:/var/www/mediawiki/extensions/YouTube:ro
    restart: always
  mediawiki_mysql:
    image: mysql:5.7
    container_name: mediawiki_mysql
    env_file: .env.mysql
    volumes:
    - mediawiki_mysql:/var/lib/mysql
    restart: always
volumes:
  mediawiki_images:
  mediawiki_mysql:
