---
  - name: Adding dd-agent to docker group
    user: name='dd-agent'
          groups='docker'
          append=yes

  - name: Check if docker was restarted yet
    command: docker info
    register: docker_restarted
    changed_when: docker_restarted.stdout.find('overlay2') == -1

  - name: Restart docker service
    shell: systemctl restart docker
    when: docker_restarted.stdout.find('overlay2') == -1

  - name: Configure datadog service to start after docker
    lineinfile:
       dest: /lib/systemd/system/datadog-agent.service
       regexp: '^After='
       line: "After=network.target docker.service"
       state: present
    notify: restart datadog-agent

  - name: Docker cleanup script copy
    copy:
      src: 'files/docker-cleanup.sh'
      dest: "/usr/sbin/docker-cleanup.sh"
      owner: 'root'
      group: 'root'
      mode: '0700'
  - name: Docker cleanup cron
    cron:
      name: "docker-cleanup"
      minute: "0"
      hour: "2"
      job: "/usr/sbin/docker-cleanup.sh"
