---
# common playbook

- include: datadog.yml
- include: postgres.yml
- hosts: all
  name: Common Play
  become: yes
  become_user: root
  roles:
    - users
    - sudo
    - sshd
    - ufw
    # - ntp
    - timezone
    # - crontab

- hosts: docker
  become: yes
  become_user: root
  roles:
    - docker
    - docker-compose
  tags:
    - runner
    - docker

# - hosts: ci-runners
#   become: yes
#   become_user: root
#   roles:
#     - gitlab-ci-multi-runner
#   tags:
#     - runner
