---
# common playbook
- hosts: all
  name: LibreHealth Common Play
  become: yes
  become_user: root
  roles:
    - users
    - sudo
    - sshd
    - ufw
    - timezone
    - unattended-upgrades
  tasks:
   - include: tasks/hostname.yml # should happen before installing datadog
