---
# common playbook
- hosts: all
  name: LibreHealth Common Play
  become: yes
  become_user: root
  roles:
    - security
    - timezone
    - users
    - ufw
  tasks:
   - import_tasks: tasks/hostname.yml # should happen before installing datadog
   - import_tasks: tasks/updates.yml
   - import_tasks: tasks/cleanup.yml
