- hosts: datadog
  name: Datadog Play
  become: yes
  roles:
    - datadog
  tasks:
   - import_tasks: tasks/updates.yml
   - import_tasks: tasks/extra-monitoring.yml
  handlers:
    - import_tasks: handlers/monitoring.yml

- hosts: www
  name: Datadog Play to add LE Cert Expiry monitoring
  become: yes
  tasks:
    - import_tasks: tasks/extra-tls.yml
  handlers:
    - import_tasks: handlers/monitoring.yml
