- hosts: docker
  name: LibreHealth Docker play
  become: yes
  become_user: root
  roles:
    - docker
  tasks:
    - include: tasks/docker-install-hacks.yml
  handlers:
    - include: handlers/monitoring.yml
