- hosts: datadog
  name: Datadog Play
  become: yes
  roles:
    - datadog
  tasks:
   - include: tasks/updates.yml
   - include: tasks/extra-monitoring.yml
  handlers:
    - include: handlers/monitoring.yml
