- hosts: tomcat
  name: LibreHealth Tomcat Play
  become: yes
  become_user: root
  roles:
    - java
    - tomcat
  tasks:
    - name: Adding existing ci user to tomcat group
      user: name='ci'
        groups='tomcat8'
        append=yes
