---
# Playbook for provisioning ssl certs using certbot. Additional variables
# specified in host_vars.
- hosts: www
  name: "Let's Encrypt Play"
  become: yes
  become_user: root
  roles:
    - dhparam
    - letsencrypt
