# from galaxy (keep alphabetical by role name)
# uncomment when geerlingguy/ansible-role-admi#9 or #12 is merged.
# - src: geerlingguy.adminer
#   name: adminer
- src: geerlingguy.apache
  name: apache
- src: geerlingguy.composer
  name: composer
- src: Datadog.datadog
  name: datadog
- src: geerlingguy.docker
  name: docker
- src: gronke.dhparam
  name: dhparam
- src: eRadical.ansible-gitlab-runner
  name: gitlab-ci-multi-runner
- src: zerohacks.imagemagick
  name: imagemagick
- src: geerlingguy.java
  name: java
- src: geerlingguy.mysql
  name: mysql
- src: geerlingguy.php
  name: php
- src: ANXS.postgresql
  name: postgresql
- src: jaywink.letsencrypt
  name: letsencrypt
- src: hmlkao.docker_mailserver
  name: mailserver
# uncomment when geerlingguy/ansible-role-nginx#125 is merged
# - src: geerlingguy.nginx
#   name: nginx
- src: geerlingguy.security
  name: security
- src: softasap.sa-tomcat
  name: tomcat

# from git
- name: adminer
  src: https://github.com/robbyoconnor/ansible-role-adminer.git
  version: force-download-if-old
- name: crontab
  src: https://github.com/yatesr/ansible-crontab.git
  version: dd8944f44675af0d2e14741619043fd60a921dd5
- name: nginx # remove when geerlingguy/ansible-role-nginx#125 is merged
  src: https://github.com/robbyoconnor/ansible-role-nginx.git
  version: add-ipv6-support
- name: ntp
  src: https://github.com/yatesr/ntp.git
  version: 08fd3721fe6c47bd7b02bfec2af5bd47f0dd3da8
- name: postfix
  src: https://github.com/petemcw/ansible-role-postfix.git
  version: 6772b873a877d393c290203e1f60219ce8df320d
- name: ssl-keys
  src: https://github.com/cintiadr/ansible-sslkeys.git
  version: 49292d68ca1309c9ed78c6a3404f0aaf3ad9829b
- name: timezone
  src: https://github.com/yatesr/ansible-timezone.git
  version: 854af629e6740c92b9098026148906643a13465c
- name: ufw
  src: https://github.com/yatesr/ansible-ufw.git
  version: f0f7615a9b1c03f29d501e169caa9ea2538cdded
- name: users
  src: https://github.com/yatesr/ansible-users.git
  version: efe5922cc2790256d7917f90728c7b5e2d14f990
