# from galaxy (keep alphabetical by role name)
- src: geerlingguy.adminer
  name: adminer
- src: andrewrothstein.curl # docker role depends
- src: geerlingguy.apache
  name: apache
- src: geerlingguy.composer
  name: composer
- src: Datadog.datadog
  name: datadog
- src: andrewrothstein.docker
  name: docker
- name: docker-compose
  src: franklinkim.docker-compose
- src: gronke.dhparam
  name: dhparam
- src: eRadical.ansible-gitlab-runner
  name: gitlab-ci-multi-runner
- src: zerohacks.imagemagick
  name: imagemagick
- src: geerlingguy.java
  name: java
- src: geerlingguy.mysql
  name: mysql
- src: geerlingguy.php
  name: php
- src: geerlingguy.php-versions
  name: php-versions
- src: ANXS.postgresql
  name: postgresql
- src: jaywink.letsencrypt
  name: letsencrypt
# uncomment when geerlingguy/ansible-role-nginx#125 is merged
# - src: geerlingguy.nginx
#   name: nginx
- src: softasap.sa-tomcat
  name: tomcat
- src: Luzifer.ubuntu-unattended-upgrades
  name: unattended-upgrades

# from git
- name: crontab
  src: https://github.com/yatesr/ansible-crontab.git
  version: dd8944f44675af0d2e14741619043fd60a921dd5
- name: nginx # remove when geerlingguy/ansible-role-nginx#125 is merged
  src: https://github.com/robbyoconnor/ansible-role-nginx.git
  version: add-ipv6-support
- name: ntp
  src: https://github.com/yatesr/ntp.git
  version: 08fd3721fe6c47bd7b02bfec2af5bd47f0dd3da8
- name: postfix
  src: https://github.com/petemcw/ansible-role-postfix.git
  version: 6772b873a877d393c290203e1f60219ce8df320d
- name: sshd
  src: https://github.com/yatesr/ansible-sshd.git
  version: e0447b8a6dabcb43712004cd2291f795b21f6b8a
- name: ssl-keys
  src: https://github.com/cintiadr/ansible-sslkeys.git
  version: 49292d68ca1309c9ed78c6a3404f0aaf3ad9829b
- name: sudo
  src: https://github.com/cintiadr/ansible-sudo.git
  version: 17215cb95018aae1810b826e544fb7280c7d0443
- name: timezone
  src: https://github.com/yatesr/ansible-timezone.git
  version: 854af629e6740c92b9098026148906643a13465c
- name: ufw
  src: https://github.com/yatesr/ansible-ufw.git
  version: f0f7615a9b1c03f29d501e169caa9ea2538cdded
- name: users
  src: https://github.com/yatesr/ansible-users.git
  version: efe5922cc2790256d7917f90728c7b5e2d14f990
