# from galaxy (keep alphabetical by role name)
- src: geerlingguy.apache
  name: apache
- src: geerlingguy.composer
  name: composer
- src: Datadog.datadog
  name: datadog
- src: andrewrothstein.docker
  name: docker
- src: michaelcontento.docker-compose
  name: docker-compose
- src: zerohacks.imagemagick
  name: imagemagick
- src: geerlingguy.java
  name: java
- src: geerlingguy.php
  name: php
- src: grim-fendango.postgresql
  name: postgresql
- src: jaywink.letsencrypt
  name: letsencrypt
- src: geerlingguy.nginx
  name: nginx
- src: softasap.sa-tomcat
  name: tomcat
