---
# Update playbook, Run with --check -v first to determine packages being upgraded
- hosts: all
  sudo: yes

  tasks:
    - name: Update Debian based distros
      apt: update_cache=yes
           cache_valid_time=600
           upgrade=yes
      when: ansible_os_family == 'Debian'

    - name: Update RedHat based distros
      yum: name=*
           state=latest
      when: ansible_os_family == 'RedHat'
